name: 'Setup environment'
inputs:
  python-version:
    required: true
    default: '3.10'

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install ruff
      uses: astral-sh/ruff-action@v3
      with:
        version-file: "pyproject.toml"
    - run: make install-dev
      shell: bash
