name: 'Setup environment'
inputs:
  python-version:
    required: true
    default: '3.10'

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install uv
      uses: astral-sh/setup-uv@v6
    - run: make install-dev
      shell: bash
