# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-xml
      - id: check-json
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: fix-byte-order-marker
      - id: end-of-file-fixer
      - id: detect-private-key
      - id: name-tests-test
        exclude: tests/utils.py
      - id: requirements-txt-fixer
      - id: fix-encoding-pragma
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.12.0
    hooks:
      - id: reorder-python-imports
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.12.5"
    hooks:
      - id: ruff
        args: ["--fix", --max-line-lenght=88]
      - id: ruff-format
