name: 'Setup environment'
inputs:
  python-version:
    required: true
    default: '3.10'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4.1.0
      with:
        fetch-depth: 50
        lfs: true
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install poetry
      uses: abatilo/actions-poetry@v2
    - name: Setup local environment
      run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local
    - uses: actions/cache@v4
      name: Cache for the virtual environment
      with:
        path: ./.pymiles
        key: pymiles-${{ hashFiles('poetry.lock') }}
    - run: make install-dev
