name: Publish to PyPI
on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - run: sudo apt -y update
    - uses: actions/checkout@v4
    - name: Setup the environment
      uses: ./.github/actions/setup
    - name: Build release files
      run: make release
    - name: Upload the packages
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

  publish-to-testpypi:
    name: Publish milespy to TestPyPI
    needs:
    - build
    runs-on: ubuntu-22.04
    environment:
      name: pypi
      url: https://test.pypi.org/p/milespy
    permissions:
      id-token: write
    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish distribution 📦 to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1

  publish-to-pypi:
    name: Publish milespy to PyPI
    if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
    needs:
    - build
    runs-on: ubuntu-22.04
    environment:
      name: pypi
      url: https://pypi.org/p/milespy
    permissions:
      id-token: write
    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
