name: Tests and documentation build
on:
  push:
  pull_request:

concurrency:
  group: "${{ github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    strategy:
      matrix:
        python-version:
        - '3.8'
        - '3.9'
        - '3.10'
        - '3.11'
        - '3.12'
    steps:
    - run: sudo apt -y update && sudo apt-get -y install git-lfs
    - uses: actions/checkout@v4.1.0
      with:
        fetch-depth: 50
        lfs: true
    - name: Setup the environment
      uses: ./.github/actions/setup
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run tests
      run: PYMILES_AUTO_DOWNLOAD=1 PYMILES_REPOSITORY_FOLDER=/tmp/ make tests
    - name: Upload artifacts
      uses: actions/upload-artifact@v4.1.0
      if: always()
      with:
        name: "${{ github.job }}-python${{ matrix.python-version }}"
        path: test_results/
  build-doc:
    needs: test
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
    - run: apt -y update && apt-get -y install pandoc git-lfs
    - uses: actions/checkout@v4.1.0
      with:
        fetch-depth: 50
        lfs: true
    - name: Setup the environment
      uses: ./.github/actions/setup
    - run: poetry run pip install jupyter
    - name: Build documentation
      run: make doc
