name: pymiles/pymiles-dev
on:
  push:
  pull_request:
  workflow_dispatch:
concurrency:
  group: "${{ github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    strategy:
      matrix:
        python-version:
        - '3.8'
        - '3.9'
        - '3.10'
        - '3.11'
        - '3.12'
    steps:
    - run: apt -y update && apt-get -y install git-lfs
    - uses: actions/checkout@v4.1.0
      with:
        fetch-depth: 50
        lfs: true
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install poetry
      uses: abatilo/actions-poetry@v2
    - name: Setup local environment
      run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local
    - uses: actions/cache@v3
      name: Cache for the virtual environment
      with:
        path: ./.venv
        key: venv-${{ hashFiles('poetry.lock') }}
    - run: make install-dev
    - run: PYMILES_AUTO_DOWNLOAD=1 PYMILES_REPOSITORY_FOLDER=/tmp/ make tests
    - uses: actions/upload-artifact@v4.1.0
      if: always()
      with:
        name: "${{ github.job }}"
        path: test_results/
  build-doc:
    needs: test
    runs-on: ubuntu-22.04
    container:
      image: python:3.10
    timeout-minutes: 60
    steps:
    - run: apt -y update && apt-get -y install pandoc git-lfs
    - uses: actions/checkout@v4.1.0
      with:
        fetch-depth: 50
        lfs: true
    - uses: actions/download-artifact@v4.1.0
    - run: pip install poetry && poetry config virtualenvs.create false
    - run: make prepare-dev
    - run: . .pymiles
    - run: make install-dev
    - run: poetry run pip install jupyter
    - run: make doc
