name: Tests
on:
  push:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  lint-format:
    runs-on: ubuntu-22.04
    steps:
      - run: sudo apt -y update
      - uses: actions/checkout@v4
      - name: Setup the environment
        uses: ./.github/actions/setup
      - run: make lint
      - run: make format
  test:
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    if: ${{ ! contains(github.event.head_commit.message, '[no test]') }}
    strategy:
      matrix:
        python-version:
        - '3.8'
        - '3.9'
        - '3.10'
        - '3.11'
        - '3.12'
    steps:
    - run: sudo apt -y update
    - uses: actions/checkout@v4
    - name: Setup the environment
      uses: ./.github/actions/setup
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run tests
      run: MILESPY_AUTO_DOWNLOAD=1 MILESPY_REPOSITORY_FOLDER=/tmp/ make tests
    - name: Creating coverage folder
      if: matrix.version == '3.10'
      run: |
        mkdir -p coverage
    - name: Coverage Bagdge
      if: matrix.version == '3.10'
      uses: tj-actions/coverage-badge-py@v1.8
      with:
        output: coverage/coverage.svg
    - name: Publish coverage report to coverage-badge branch
      if: matrix.version == '3.10'
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: coverage-badge
        folder: coverage
    - name: Upload artifacts
      uses: actions/upload-artifact@v4.1.0
      if: always()
      with:
        name: "${{ github.job }}-python${{ matrix.python-version }}"
        path: test_results/
